name = "Rose Garden"
author = "Rose, Gibby, Katie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00efa49117c6df6933dbb7dc95e83f2eec63967ec76f19f0d7e2e63ffc62c919"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
